



########

import os
import time
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# Setup
website_url = "https://www.1001freefonts.com/"


url_code_unclear = [


    "Youtube-Strikes",
    "Youtubepia",
    "Yowesta",
    "Yoxall",
    "Yrsa",
    "Ysgarth",
    "Yuanita",
    "Yuanitta",
    "Yudistira",
    "Yugathor",
    "Yuge",
    "Yugen",
    "Yugitoy",
    "Yugoslavia",
    "Yuk-Ngexi",
    "Yukarimobile",
    "Yukikato",
    "Yukita-Creative",
    "Yukon-Gold",
    "Yukon-Tech",
    "Yuletide",
    "Yuletide-Season",
    "Yulinda-Script",
    "Yulista-Sister",
    "Yulita-Script",
    "Yuliya",
    "Yullia-Ketty",
    "Yum-Nub-Extended",
    "Yum-Yum",
    "Yumeira-Monogram",
    "Yumernub",
    "Yuminer",
    "Yummy-Cupcakes",
    "Yummy-Dinner",
    "Yummy-Lollipop",
    "Yummy-Mummy",
    "Yummy-Nubs",
    "Yummy-Pizza",
    "Yumoda",
    "Yunan",
    "Yurine-Overflow",
    "Yussan",
    "Yustia-Script",
    "Yustika",
    "Yustinja",
    "Yytrium-Dioxide",
    "X-Bones",
    "X-Classified",
    "X-Code-From-East",
    "X-Fighters",
    "X-Termination",
    "X-Cryption",
    "X-Grid",
    "X-Racer",
    "X.-Template",
    "Xabilon",
    "Xabiya",
    "Xacode",
    "Xacose",
    "Xagetif",
    "Xal-Terion",
    "Xamire",
    "Xanax",
    "Xander-Bruce",
    "Xander-Swordfish",
    "Xantegrode-Signature",
    "Xanthie",
    "Xanthousy",
    "Xantiqoo",
    "Xantorid",
    "Xaphan",
    "Xarrovv",
    "Xavier-Ashleigh",
    "Xavierace",
    "Xayax",
    "XBall",
    "Xbka",
    "Xcelsion",
    "Xdevilix",
    "Xeare",
    "Xegir",
    "Xekova",
    "Xenia-Urshina",
    "Xenik",
    "Xenippa",
    "Xenku",
    "Xeno-Demon",
    "Xeno-Tribal",
    "Xenophobia",
    "Xenophone",
    "Xenos",
    "Xenosphere",
    "Xenowort",
    "Xephyr",
    "Xepon",
    "Xeppelin",
    "Xerker",
    "Xero-Typique",
    "Xero's-Retreat",
    "Xerography",
    "Xeros-Karma",
    "Xeros-Proof",
    "Xeros-Punishment",
    "Xeros-Theorem",
    "Xerox-Malfunction",
    "Xerulah",
    "Xerxes",
    "xghostx",
    "Xharp",
    "Xhume",
    "Xi-Beronne",
    "Xiao-Gao",
    "Xiaxide",
    "Xide",
    "Xikas",
    "Xilo-Galdino",
    "Xilo-In-Zodiac",
    "Xilo-Prosa",
    "Xiomara",
    "Xiparos",
    "Xiparos-Lombard",
    "Xiphos",
    "Xipital",
    "Xirod",
    "Xirwena",
    "Xmas",
    "Xmas-Bells",
    "Xmas-Caps",
    "Xmas-Clipart-1",
    "Xmas-Clipart-2",
    "Xmas-Ginger-2005",
    "Xmas-Gingerbread",
    "Xmas-Lights",
    "Xmas-Lite",
    "Xmas-Sweater-Stitch",
    "Xmas-Xpress",
    "Xmas-Year-Zero",
    "XmasTerpiece",
    "Xoana-Rush",
    "Xodohtro-Nu",
    "Xolo",
    "Xolonium",
    "Xolto",
    "Xomai",
    "Xoxoxo",
    "Xped",
    "Xperage",
    "Xperience-Pasta",
    "Xperimentypo-FS",
    "Xray-Ted",
    "XRaytid",
    "Xsderminatoer",
    "Xsotik",
    "Xspiked",
    "Xtra",
    "Xtra-Flexi-Disc",
    "Xtraordinary",
    "Xtrapower",
    "Xtreem",
    "Xtreem-2",
    "Xtreme-Bike",
    "Xtreme-Chrome",
    "Xtrusion",
    "Xutwef",
    "XuYanDok",
    "XXon-XXoff",
    "Xxrdcore",
    "Xyling",
    "Xylitol",
    "Xylophones",  "Zabars",
    "Zabatana-Poster",
    "Zabiat",
    "Zacatecas",
    "Zachary-Binx",
    "Zachian",
    "Zack-And-Sarah",
    "Zacken",
    "Zackerman",
    "Zado",
    "Zafrilus",
    "Zag-Zag",
    "Zagga",
    "Zaghara",
    "Zahra",
    "Zahra-Lovely",
    "Zainiver",
    "Zaitun",
    "Zakenstein",
    "Zakilla",
    "Zaklady",
    "Zakosten",
    "Zalerin",
    "Zaleski",
    "Zalina",
    "Zalitta-Script-Signature",
    "Zallman-Caps",
    "Zaloga-Typeface",
    "Zamanda",
    "Zamboni-Joe",
    "Zamboora",
    "Zamilla",
    "Zamira",
    "Zamora",
    "Zamoretta",
    "Zamrud-And-Khatulistiwa",
    "Zanden",
    "Zaniah",
    "Zanie-Brovia",
    "Zanky",
    "Zanolia",
    "Zantroke",
    "Zany-Races",
    "Zany-Sharp",
    "Zanzabar",
    "Zap-Control",
    "Zap-Deal",
    "Zapped-Sticks",
    "Zara-Amorett",
    "Zarah",
    "Zarame",
    "Zarathos",
    "Zarla",
    "Zarra",
    "Zasline",
    "Zasqie",
    "Zasquora",
    "Zathira",
    "Zatiyan",
    "Zavanna",
    "Zay",
    "Zayttan",
    "Zaz-Gorila",
    "ZDYK-Aquarius",
    "Zdyk-Capricorn",
    "Zdyk-Gemini",
    "Zdyk-Leo",
    "Zdyk-Libra",
    "Zdyk-Pisces",
    "Zdyk-Sagittarius",
    "Zdyk-Scorpio",
    "Zealot",
    "Zealousy",
    "Zeanica",
    "Zebra",
    "Zebra-Advert",
    "Zebra-Blobs",
    "Zebra-Cross",
    "Zebra-Disco",
    "Zebraesq",
    "Zebraliner",
    "Zebrra",
    "Zebru",
    "Zebulon",
    "Zebulona-Victoria",
    "Zed-Said",
    "ZedEx-Eight-T-One",
    "Zee-Lance",
    "Zefir",
    "Zeit-Geisterbahn",
    "Zekat",
    "Zekilo",
    "Zekista",
    "Zekton",
    "Zelda-DX",
    "Zella",
    "Zelta-Six",
    "Zen-Frax",
    "Zen-Frax-Condensed",
    "Zen-Masters",
    "Zen-Monolith",
    "Zen3",
    "Zenarico",
    "Zenda",
    "Zeneon",
    "Zenfyrkalt",
    "Zenghief",
    "Zengo",
    "Zenith",
    "Zenith-2000",
    "Zenittash",
    "Zenlith",
    "Zenone",
    "Zenova-Xeno",
    "Zenseo",
    "Zensyrom",
    "Zentaiges",
    "Zentenar-Fraktur",
    "Zentran",
    "Zenyth",
    "Zenzai-Itacha",
    "Zeora",
    "Zephan-Typeface",
    "Zephira",
    "Zephiroth",
    "Zephyr-Jubilee",
    "Zephyr-Script",
    "Zephyre-Conquer",
    "Zephyrean",
    "Zephyrush",
    "Zeppelin",
    "Zepplines",
    "Zerafoc",
    "Zerafoc-Italic",
    "Zerico-Square",
    "Zero",
    "Zero-And-Zero-Is",
    "Zero-Athletics",
    "Zero-College",
    "Zero-Hour",
    "Zero-Hype",
    "Zero-Mistake",
    "Zero-Points",
    "Zero-Prime",
    "Zero-Theory",
    "Zero-Velocity",
    "Zerocalcare",
    "Zerocalcare-Script",
    "Zeroes-One",
    "Zeroes-Three",
    "Zeroes-Two",
    "Zeronero",
    "Zerpixl",
    "Zerpixl-Dark",
    "Zestful",
    "Zeta-Reticuli",
    "Zeta-Sentry",
    "Zetland",
    "Zettosaid",
    "Zetwih",
    "Zeus-Land",
    "Zeuty-Script",
    "Zevallya",
    "Zewkila",
    "Zeyada",
    "Zeyatte-Kareety",
    "Zeynal-Abdin",
    "Zhafir",
    "Zhang-QA",
    "Zholly-Display",
    "Zhukov-Zippo",
    "Zian",
    "Zidan",
    "Zierinitialen",
    "Zieruk",
    "Zig",
    "Zig-Zag",
    "Zigasto",
    "Ziggy",
    "Ziggy-Zoe",
    "Zigzag-Displays",
    "Zigzageo",
    "Zigzagzoel",
    "Zilap-Africa",
    "Zilap-Black-Storm",
    "Zilap-Geometrik",
    "Zilap-Monograma",
    "Zilap-Oriental",
    "Zilap-Sleep",
    "Zilap-Urban",
    "Zilla-Slab",
    "Zillah-Modern",
    "Zimeta",
    "Zinedka",
    "Zing-Ding",
    "Zing-Easy",
    "Ziona",
    "Zip-Down",
    "Zipper-Blues",
    "Zipper-Fries",
    "Zipper-Heart",
    "Zipple-Bold",
    "Zippo",
    "Zippy",
    "Zirconia",
    "Zirconian",
    "Zit-Cream",
    "Zita",
    "Ziviliam-Monogram",
    "Zlatoust-Chaos",
    "Znikomit",
    "Znikomit-No-24",
    "Znikomit-No-25",
    "Znort-3000",
    "Znowwhite",
    "Zoa-Elephantesque",
    "Zocode",
    "Zodiac-Key",
    "Zodiac-St",
    "Zodiastic",
    "Zodillin",
    "Zoero",
    "Zoetrope",
    "Zoey-Elizabeth",
    "Zofia-Larsonty",
    "Zoidal",
    "Zollern",
    "Zoloft",
    "Zoltan-Kiss",
    "Zombi-Predator",
    "Zombie",
    "Zombie-Apocalypse",
    "Zombie-Army",
    "Zombie-Brains",
    "Zombie-Brush",
    "Zombie-City",
    "Zombie-Control",
    "Zombie-Food",
    "Zombie-Garden-Party",
    "Zombie-Holocaust",
    "Zombie-Monster",
    "Zombie-Morning",
    "Zombie-Mummy",
    "Zombie-Noize",
    "Zombie-Party",
    "Zombie-Queen",
    "Zombie-School",
    "Zombie-Scratch",
    "Zombie-Shooting",
    "Zombie-Slayer",
    "Zombie-State",
    "Zombie-Stitch",
    "Zombie-Treats",
    "Zombie-Zone",
    "Zombiebites",
    "Zombieland",
    "Zombies",
    "Zombies-Reborn",
    "Zombified",
    "Zomblo",
    "Zomtam-Thai",
    "Zona-Armada",
    "Zondas",
    "Zone-Rider",
    "Zonular",
    "Zoo-Carnival",
    "Zoologic",
    "Zooma",
    "Zooming-Track",
    "Zoomrunner",
    "Zoon-Hoot",
    "Zoot-Allures",
    "Zorgho",
    "Zorque",
    "Zorros",
    "Zorus-Serif",
    "Zosilla",
    "Zothique",
    "Zounderkite",
    "Zrnic",
    "Zsylett",
    "Zsylett-Pro",
    "Zsynor",
    "Zsyraph",
    "Zuber-Future",
    "Zuber-Stone",
    "Zuber-Tech",
    "Zud-Juice",
    "Zudime",
    "Zumanji-Valkalari",
    "Zupa-Lumpa",
    "Zupagargonizer-T",
    "Zuper-Skew",
    "Zuriah",
    "Zurklez",
    "Zwiebelfisch",
    "ZX-Spectrum-7",
    "ZX-Spectrum-Keyboard",
    "Zyborgs",
    "Zymbols",
    "Zyphyte",
    "Zyprian"
]









x=0
url_output = []

for item in url_code_unclear:
    if url_output.__contains__(item):  
        x=3
    else:
        url_output.append(item)


testing_list = [ "A-Anti-Corona",    "A-Bebedera",    "A-Bit-Empty"]


url_end = '.font'


chrome_driver_path = '/opt/homebrew/bin/chromedriver'  # Specify the path to your chromedriver

# Ensure the download directory exists
download_dir = "/Users/alexkoong/Desktop/downloaded_fonts_june28"
if not os.path.exists(download_dir):
    print("STOPPPP")
    os.makedirs(download_dir)

options = webdriver.ChromeOptions()
prefs = {
    "download.default_directory": download_dir,
    "download.prompt_for_download": False,
    "safebrowsing.enabled": True,
    "profile.default_content_settings.popups": 0,
    "directory_upgrade": True
}
options.add_experimental_option("prefs", prefs)

# Create a Service object with the path to chromedriver
service = Service(chrome_driver_path)

# Initialize the webdriver with the Service object and options
driver = webdriver.Chrome(service=service, options=options)




for url in url_code_unclear:

    website_url = 'https://www.1001freefonts.com/' + url + '.font'



    try:
        driver.get(website_url)
        driver.execute_script("window.scrollTo(0, 500);")
        time.sleep(3)

        download_button = driver.find_element(By.CSS_SELECTOR, "div[class='downloadButtonElement'] a")
        driver.execute_script("arguments[0].click();", download_button)
        time.sleep(3)
    finally:
        print(website_url)

driver.quit()
