services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    runtime: nvidia
    image: react-flask-app-api
    ports:
      - "80:80"
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: react-flask-app-client
    ports:
      - "443:443"