FROM nvidia/cuda:12.8.0-base-ubuntu20.04
# Install system dependencies
RUN apt-get update && \
    apt-get install -y python3 python3-pip

WORKDIR /app

COPY ./backend/requirements.txt ./backend/api.py ./backend/diffusion.py ./
RUN python3 -m pip install -r ./requirements.txt
ENV FLASK_ENV=production

EXPOSE 8080
CMD ["gunicorn", "-b", ":8080", "api:app"]